[repository]
name = "awesome_like_workspaces"
authors = ["gomfol12"]
commit_pins = [
    ["46174f78b374b6cea669c48880877a8bdcf7802f", "0edb2ad0e5193d151396a21cef81f9d62a730f7a"], # 0.51.0
    ["9958d297641b5c84dcff93f9039d80a5ad37ab00", "e7c59b12f7d200c5711675e4684bcff399dcefb6"], # 0.49.0
    ["04ac46c54357278fc68f0a95d26347ea0db99496", "0305d94f1c4b105a5666e40ab4e9ba09d78a5edf"], # 0.47.0
    ["0bd541f2fd902dbfa04c3ea2ccf679395e316887", "b47f6875d6023a8a9aa043f892b4b7ec6e3fcd23"], # 0.46.2
    ["f5fa84554ffe55e29a397014964238be89ffa54d", "863936f146ea62bb20b1b349a791d4cc9435c351"], # 0.45.0
    ["9a09eac79b85c846e3a865a9078a3f8ff65a9259", "5957a69670ef843eaac1fcc83e2f930cfef0ceb8"], # 0.42.0
]

[awesome_like_workspaces]
description = "awesome_like_workspaces plugin for Hyprland"
authors = ["gomfol12"]
output = "build/libawesome_like_workspaces.so"
build = [
    "cmake -B build -S .",
    "cmake --build build"
]
